server:
  port: 8000

spring:
  application:
    name: auth-server
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: springcloud-nacos-server
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        min-idle: 0
        max-idle: 8

