server:
  port: 8888

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        # 路径id 唯一自定义的名称
#        - id: product-server
#          # 此处需要使用Lb协议
#          uri: lb://product-server
#          predicates:
#            # 断言，路径相匹配的进行路由  匹配base请求路径后面的接口
#            - Path=/product/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8090/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
